apiVersion: v1
kind: Secret
metadata:
  name: watchtower-secrets
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  db-url: cG9zdGdyZXNxbCtwc3ljb3BnMjovL3dhdGNodG93ZXI6Q0hBTkdFX1RISVNfUEFTU1dPUkRAZGI6NTQzMi93YXRjaHRvd2Vy
  db-password: Q0hBTkdFX1RISVNfUEFTU1dPUkQ=
  api-key: eW91ci1zZWN1cmUtYXBpLWtleS1oZXJl
  admin-key: eW91ci1zZWN1cmUtYWRtaW4ta2V5LWhlcmU=
  llm-api-key: eW91ci1sbG0tYXBpLWtleS1oZXJl
