version: "3.9"

services:
  db-main:
    env_file:
      - .env
    image: postgres:15
    container_name: db-main
    restart: unless-stopped
    environment:
      POSTGRES_USER: watchtower
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: watchtower_main
    ports:
      - "5432:5432"
    volumes:
      - db_main_data:/var/lib/postgresql/data

  db-test:
    env_file:
      - .env
    image: postgres:15
    container_name: db-test
    restart: unless-stopped
    environment:
      POSTGRES_USER: watchtower-test
      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD}
      POSTGRES_DB: watchtower_test
    ports:
      - "5433:5432"
    volumes:
      - db_test_data:/var/lib/postgresql/data

volumes:
  db_main_data:
  db_test_data:
